version: "3"

services:
  vb-ama-utilities-api:
    image: vb-ama-utilities-api
    build: .
    restart: always
    volumes:
      - ./:/webapps
    ports:
      - 9999:5005
    command: supervisord -n -c /etc/supervisor.d/service.conf

  vb-ama-utilities-worker:
    image: vb-ama-utilities-worker
    build: .
    restart: always
    volumes:
      - ./:/webapps
    command: supervisord -n -c /etc/supervisor.d/worker.conf

  vb-ama-utilities-scheduled:
    image: vb-ama-utilities-scheduled
    build: .
    restart: always
    volumes:
      - ./:/webapps
    command: supervisord -n -c /etc/supervisor.d/scheduled_job.conf
